// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTexhiSvAbrwYO60ob486E4fcwhda0spc',
    appId: '1:788835075727:web:86e3e22df132f4faa352fa',
    messagingSenderId: '788835075727',
    projectId: 'x-top-fdfe2',
    authDomain: 'x-top-fdfe2.firebaseapp.com',
    storageBucket: 'x-top-fdfe2.firebasestorage.app',
    measurementId: 'G-NMR2V8NH3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP9jmH8jHS0If908FVn1LxgbYXYZb2lbc',
    appId: '1:788835075727:android:3d6b08799989ae7ca352fa',
    messagingSenderId: '788835075727',
    projectId: 'x-top-fdfe2',
    storageBucket: 'x-top-fdfe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2e1eFaW7VKrL-Q8zuG9sJLcho7AtQBLo',
    appId: '1:788835075727:ios:9bdf679dd6136beaa352fa',
    messagingSenderId: '788835075727',
    projectId: 'x-top-fdfe2',
    storageBucket: 'x-top-fdfe2.firebasestorage.app',
    iosBundleId: 'com.example.xTop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2e1eFaW7VKrL-Q8zuG9sJLcho7AtQBLo',
    appId: '1:788835075727:ios:9bdf679dd6136beaa352fa',
    messagingSenderId: '788835075727',
    projectId: 'x-top-fdfe2',
    storageBucket: 'x-top-fdfe2.firebasestorage.app',
    iosBundleId: 'com.example.xTop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTexhiSvAbrwYO60ob486E4fcwhda0spc',
    appId: '1:788835075727:web:8f3a435da1c439c1a352fa',
    messagingSenderId: '788835075727',
    projectId: 'x-top-fdfe2',
    authDomain: 'x-top-fdfe2.firebaseapp.com',
    storageBucket: 'x-top-fdfe2.firebasestorage.app',
    measurementId: 'G-PBF8V6VC0K',
  );
}
